@startuml
' The following is the global default style (do not use Fira Code font, otherwise the Chinese will not be displayed)
skinparam DefaultFontName Microsoft YaHei
skinparam DefaultFontSize 16
skinparam ArrowColor DeepSkyBlue
' The following is the style of the actor (class)
skinparam ParticipantFontColor White
skinparam ParticipantBorderColor DeepSkyBlue
skinparam ParticipantBackgroundColor DodgerBlue
skinparam ParticipantFontSize 18
' Here is the flowchart code
actor User
User --> "AbstractAuthentication\nProcessingFilter": doFilter(...)\n/login username, password
"AbstractAuthentication\nProcessingFilter" -> "UsernamePassword\nAuthenticationFilter":attemptAuthentication(...)
"UsernamePassword\nAuthenticationFilter" --> "AbstractUserDetails\nAuthenticationProvider":authenticate(...)\nomitted ProviderManager
"AbstractUserDetails\nAuthenticationProvider" -> "DaoAuthentication\nProvider":retrieveUser(...)
"DaoAuthentication\nProvider" -> "SysUserLoginUser\nDetailsServiceImpl":**loadUserByUsername(...)**
"DaoAuthentication\nProvider" <- "SysUserLoginUser\nDetailsServiceImpl"
"AbstractUserDetails\nAuthenticationProvider" <- "DaoAuthentication\nProvider"
"AbstractUserDetails\nAuthenticationProvider" -> "DaoAuthentication\nProvider":additionalAuthenticationChecks(...)
"DaoAuthentication\nProvider" --> "DaoAuthentication\nProvider":**compare password**
"AbstractAuthentication\nProcessingFilter" <-- "DaoAuthentication\nProvider":Authentication authenticationResult = attemptAuthentication(...);
"AbstractAuthentication\nProcessingFilter" -> "AbstractAuthentication\nProcessingFilter":successfulAuthentication(...)
"AbstractAuthentication\nProcessingFilter" --> "HttpSessionSecurity\nContextRepository":**setContextInSession(...)** : session.setAttribute(this.springSecurityContextKey, context); // the context contains authenticationResult
"AbstractAuthentication\nProcessingFilter" <-- "HttpSessionSecurity\nContextRepository"
User <-- "AbstractAuthentication\nProcessingFilter"
@enduml
