@startuml
' 以下是全局默认的样式（不能使用 Fira Code 字体，否则显示不了中文）
skinparam DefaultFontName Microsoft YaHei
skinparam DefaultFontSize 16
skinparam ArrowColor DeepSkyBlue
' 以下是参与者（类）的样式
skinparam ParticipantFontColor White
skinparam ParticipantBorderColor DeepSkyBlue
skinparam ParticipantBackgroundColor DodgerBlue
skinparam ParticipantFontSize 18
' 以下是流程图代码
actor User
User --> "AbstractAuthentication\nProcessingFilter\n.doFilter(...)": /login username, password
"AbstractAuthentication\nProcessingFilter\n.doFilter(...)" -> "UsernamePassword\nAuthenticationFilter":attemptAuthentication(...)
"UsernamePassword\nAuthenticationFilter" --> "AbstractUserDetails\nAuthenticationProvider":authenticate(...)\nomitted ProviderManager
"AbstractUserDetails\nAuthenticationProvider" -> "DaoAuthentication\nProvider":retrieveUser(...)
"DaoAuthentication\nProvider" -> "SysUserLoginUser\nDetailsServiceImpl":**loadUserByUsername(...)**
"DaoAuthentication\nProvider" <- "SysUserLoginUser\nDetailsServiceImpl"
"AbstractUserDetails\nAuthenticationProvider" <- "DaoAuthentication\nProvider"
"AbstractUserDetails\nAuthenticationProvider" -> "DaoAuthentication\nProvider":additionalAuthenticationChecks(...)
"DaoAuthentication\nProvider" --> "DaoAuthentication\nProvider":**compare password**
"AbstractAuthentication\nProcessingFilter\n.doFilter(...)" <-- "DaoAuthentication\nProvider":Authentication authenticationResult = attemptAuthentication(...);
"AbstractAuthentication\nProcessingFilter\n.doFilter(...)" -> "AbstractAuthentication\nProcessingFilter\n.doFilter(...)":successfulAuthentication(...)
"AbstractAuthentication\nProcessingFilter\n.doFilter(...)" --> "HttpSessionSecurity\nContextRepository":**setContextInSession(...)** : session.setAttribute(this.springSecurityContextKey, context); // the context contains authenticationResult
"AbstractAuthentication\nProcessingFilter\n.doFilter(...)" <-- "HttpSessionSecurity\nContextRepository"
User <-- "AbstractAuthentication\nProcessingFilter\n.doFilter(...)"
@enduml
