@startuml
' The following is the global default style (do not use Fira Code font, otherwise the Chinese will not be displayed)
skinparam DefaultFontName Microsoft YaHei
skinparam DefaultFontSize 16
skinparam ArrowColor DeepSkyBlue
' The following is the style of the actor (class)
skinparam ParticipantFontColor White
skinparam ParticipantBorderColor DeepSkyBlue
skinparam ParticipantBackgroundColor DodgerBlue
skinparam ParticipantFontSize 18
' Here is the flowchart code
title JWT login flowchart
actor User
User --> "SysUserJwt\nAuthController": login(...)
"SysUserJwt\nAuthController" -> "SysUserJwt\nAuthService": login(...)
"SysUserJwt\nAuthService" -> "SysUserJwt\nAuthService": build UsernamePasswordAuthenticationToken
"SysUserJwt\nAuthService" -> "AbstractUserDetails\nAuthenticationProvider": authenticate(...)
"AbstractUserDetails\nAuthenticationProvider" --> "SysUserLoginUser\nDetailsServiceImpl": loadUserByUsername(...)
"AbstractUserDetails\nAuthenticationProvider" <-- "SysUserLoginUser\nDetailsServiceImpl"
"AbstractUserDetails\nAuthenticationProvider" --> "DaoAuthentication\nProvider": additionalAuthenticationChecks(...) **validate password**
"AbstractUserDetails\nAuthenticationProvider" <-- "DaoAuthentication\nProvider"
"SysUserJwt\nAuthService" <- "AbstractUserDetails\nAuthenticationProvider"
"SysUserJwt\nAuthService" -> "JwtToken\nProvider":generateToken(...)
"SysUserJwt\nAuthService" <- "JwtToken\nProvider":return token (username, roles, expiration, signature, ...)
"SysUserJwt\nAuthController" <- "SysUserJwt\nAuthService"
User <-- "SysUserJwt\nAuthController"
@enduml
