server:
  port: 22345

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    cn.huava: debug
    com.baomidou.mybatisplus.core.executor.BaseExecutor: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/huava?useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: huava
    password: eFS0H6_0_pkVm__o

project:
  jwt_key_base64: JsbZtEZD+oB3sMEnfbmFuqiBFGpNofZkNHTOeuXqPi8=

example:
  app:
    jwtSecret: examplesecretKey@
    jwtExpirationMs: 86400000
    jwtRefreshSecret: examplerefreshsecretKey@abcdefgh1234567890
    jwtRefreshExpirationMs: 8640000

