@startuml
' The following is the global default style (do not use Fira Code font, otherwise the Chinese will not be displayed)
skinparam DefaultFontName Microsoft YaHei
skinparam DefaultFontSize 16
skinparam ArrowColor DeepSkyBlue
' The following is the style of the actor (class)
skinparam ParticipantFontColor White
skinparam ParticipantBorderColor DeepSkyBlue
skinparam ParticipantBackgroundColor DodgerBlue
skinparam ParticipantFontSize 18
' Here is the flowchart code
title Visit secured URL with JWT token
actor User
User --> "Application\nFilterChain": internalDoFilter(...) \nvisit login url
"Application\nFilterChain" --> "JwtAuthentication\nFilter": doFilterInternal(...)
"JwtAuthentication\nFilter" -> "JwtAuthentication\nFilter": build authentication by token
"Application\nFilterChain" <-- "JwtAuthentication\nFilter"
"Application\nFilterChain" --> "Dispatcher\nServlet": service(...)
"Dispatcher\nServlet" --> "AuthorizationManager\nBeforeMethodInterceptor":attemptAuthorization(...)
"AuthorizationManager\nBeforeMethodInterceptor" --> "Security\nExpressionRoot": hasAnyRole(...)\ncheck roles
"AuthorizationManager\nBeforeMethodInterceptor" <-- "Security\nExpressionRoot"
"Dispatcher\nServlet" <-- "AuthorizationManager\nBeforeMethodInterceptor"
"Application\nFilterChain" <-- "Dispatcher\nServlet"
User <-- "Application\nFilterChain"
@enduml
